<a href="https://colab.research.google.com/github/Shankjbs571/Machine-Learning-Techniques/blob/main/MLP_W1_PA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data/Preprocessing1.csv')
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0

TypeError: 'numpy.ndarray' object is not callable

# MetaData
* Airline:The name of the airline
* Source: The source from which the service begins
* Destination: The destination where the service ends
* Route: Route the flight took.
* Dep_Time: The time when the journey starts from the source.
* Arrival_Time: Time of arrival at the destination.
* Duration: Total duration of the flight.
* Total_Stops: Total stops between the source and destination.
* Additional_Info: Additional information about the flight
* Price: The price of the ticket ▶▶▶ Target
* Month: Month of journey.
* WeekDay: Day at which journey started.
* Day: Date of the start of journey.

 [Click here to view the dataset:](https://drive.google.com/file/d/1zP38WCdZQ9StsAHTTLk72763QJQkhWrG/view)

In [7]:
#@title (1) What is the average of the flight ticket price? Write your answer correct to two decimal places.
avg_price = df['Price'].mean()
avg_price.round(3)

9027.896

In [16]:
#@title (2)During which month did the highest number of flights occur? Months are represented by numerical codes, with January corresponding to 1, February to 2, and so forth.
print(df['Month'].unique())
month_wise_group = df.groupby('Month').size()
month_wise_group

[6 3 5 4]

Month
3    2388
4     926
5    3092
6    3044
dtype: int64

In [20]:
#@title (3) Is the average price of flight tickets higher on weekends (Saturday and Sunday) or on weekdays (Remaining 5 days)?

df['Weekend'] = df['WeekDay'].isin(['Saturday ', 'Sunday'])  # True for weekend, False for weekday
average_price_weekend = df[df['Weekend']]['Price'].mean()
average_price_weekday = df[~df['Weekend']]['Price'].mean()

if average_price_weekend > average_price_weekday:
    print("Average price of flight tickets is higher on weekends.")
else:
    print("Average price of flight tickets is higher on weekdays.")

Average price of flight tickets is higher on weekends.

In [37]:
#@title (4)Two of the entries in the 'Additional_Info' column are 'No info' and 'No Info'. Replace all occurrences of 'No Info' with 'No info'. How many flights fall under airline 'IndiGo' and have 'No info' as additional information?

df['Additional_Info']=df['Additional_Info'].replace('No Info','No info')
result = df[(df['Airline']=='IndiGo') & (df['Additional_Info'] == 'No info')]
result.shape[0]

1650

In [44]:
#@title (5) Convert the values of 'Duration' into seconds. Enter the average duration (in seconds) of a flight. Enter your answer correct to two decimal places.

def convert_to_seconds(duration):
    if 'h' in duration and 'm' in duration:
        hours, minutes = duration.split('h ')
        return int(hours) * 3600 + int(minutes.replace('m', '')) * 60
    elif 'h' in duration:
        return int(duration.split('h')[0]) * 3600
    elif 'm' in duration:
        return int(duration.replace('m', '')) * 60
    else:
        return 0  # Handle cases with no 'h' or 'm'

df['Duration_seconds'] = df['Duration'].apply(convert_to_seconds)
df.head()
df['Duration_seconds'].mean()

38957.93650793651

## Apply the following functions to the columns Dep_Time and Arrival_Time:

Transform the values in the 'dep_time' and 'arrival_time' columns to represent the hour component. For instance, if an entry is 10:05 June 13 or 10:05, the corresponding value should be 10.
Then convert the time into four categories as follows:
* 5 <= hour < 12 = Morning
* 12 <= hour < 17 = Afternoon
* 17 <= hour < 20 = Evening
* 20 <= hour < 5 = Night

In [56]:

df['Dep_hour'] = df['Dep_Time'].str.split(' ').str[0].str.split(':').str[0].astype(int)
df['Arr_hour'] = df['Arrival_Time'].str.split(' ').str[0].str.split(':').str[0].astype(int)

# Function to convert hour to time of day category
def categorize_time(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 20:
        return 'Evening'
    elif 20 <= hour or hour < 5:
        return 'Night'

# Apply the function to the 'Hour' column to create a new column 'TimeOfDay'
df['TimeOfDep'] = df['Dep_hour'].apply(categorize_time)
df['TimeOfArr'] = df['Arr_hour'].apply(categorize_time)
df.drop(['Dep_hour','Arr_hour'],axis='columns')

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,Weekend,Duration_seconds,TimeOfDep,TimeOfArr
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0,False,95700,Night,Night
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0,True,97200,Afternoon,Evening
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0,False,5400,Evening,Night
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0,False,54600,Evening,Night
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0,False,30000,Evening,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9445,Air India,Banglore,Cochin,BLR → MAA → DEL,19:30,19:50,8h 55m,1 stop,In-flight meal not included,5932,6,Wednesday,12.0,False,32100,Evening,Evening
9446,IndiGo,Delhi,Cochin,DEL → BOM → COK,17:00,21:00,8h 35m,1 stop,No info,6838,3,Sunday,3.0,True,30900,Evening,Night
9447,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,07:05,19:45,15h 15m,1 stop,No info,12615,3,Saturday,9.0,False,54900,Morning,Evening
9448,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,08:20,19:50,12h 5m,1 stop,No info,10844,5,Saturday,18.0,False,43500,Morning,Evening
9449,Air India,Kolkata,Banglore,CCU → GAU → IMF → DEL → BLR,14:30,23:15,8h 45m,3 stops,No info,15145,5,Thursday,9.0,False,31500,Afternoon,Night

In [58]:
#@title (6) How many flights started in the Morning and arrived the destination at Evening?
flight_morning_to_evening = df[(df['TimeOfDep']=='Morning') & (df['TimeOfArr']=='Evening')]
flight_morning_to_evening.shape[0]

922

In [62]:
#@title (7) Encode the values of column 'WeekDay' as follows: Weekends (Sunday, Saturday) = 1 , all remaining five days = 0 What is the most frequent (mode) WeekDay
def encode(day):
  if day in ['Sunday', 'Saturday']:
    return 1
  else:
    return 0

df['Encoded_WeekDay'] = df['WeekDay'].apply(encode)

count_1 = df['Encoded_WeekDay'].value_counts()

0    6651
1    2799
Name: Encoded_WeekDay, dtype: int64

In [65]:
count_1.loc[0]
if count_1.loc[0] > count_1.loc[1]:
  mode = 'WeekDays'
else:
  mode = 'Weekends'

print(f'The Most Frequent Mode is {mode}')

The Most Frequent Mode is WeekDays